@startuml

'acteurs
actor "Utilisateur" as u order 1
control "application" as a order 2
database "serveur centrale" as d order 4
collections "Utilisateurs connectés" as u2 order 5

'parametres
title Diagramme global simplifié
autonumber 

'actions
u2 -> d : listeDesFichierPossédé
create "Serveur" as s order 3
a -> s : lancerServeu()
a -> d : listeDesFichierPossédé
u -> a : listeDesFichiersTelechargeable()
a -> d : listeDesFichiersTelechargeable()
d --> a : String liste
a --> u : String liste
u -> a : telecharger(String nomDuFichier)
a -> d : utilisateursAyant(String nomDuFichier)
d --> a : listeDesUtilisateurs
opt ratio est bon
    loop tant que fichier non complet
        par 
            a -> u2 : telechargerBloc(String nomDuFichier, int numeroBloc)
            u2 --> a : blocDuFichier
            a --> d : long tailleRecue
        end
    end
end
a -> d : listeDesFichierPossédé
u -> a : quitter


@enduml